version: 2

sources:
  - name: raw
    schema: raw_data_circle
    loader: bigquery 
    tables:
      - name: cc_parcel_product
        identifier: raw_cc_parcel_product
        columns:
          - name: parcel_id
            tests:
            - unique
            - not_null
      - name: cc_parcel
        identifier: raw_data_circle
        columns:
          - name: parcel_id
            tests:
              - unique
              - not_null