version: 2

sources:
  - name: raw
    database: unique-atom-475008-g2
    schema: gz_raw_data_2
    loader: bigquery 
    tables:
      - name: product 
        identifier: raw_gz_product 
      - name: sales
        identifier: raw_gz_sales
      - name: ship
        identifier: raw_gz_ship
    
      


 