version: 2

sources:
  - name: gz_raw_data_2
    database: unique-atom-475008-g2
    schema: "{{ target.schema }}"
    loader: bigquery
    freshness: 
      error_after:
        count: 24
        period: hour
      warn_after:
        count: 12
        period: hour
    tables:
      - name: raw_gz_product
      - name: raw_gz_sales
      - name: raw_gz_ship
    
      


 